#!/usr/bin/env bash
#
# Summary: Show out of date installed packages
#
#   @see https://github.com/Homebrew/homebrew-bundle
# Usage: pm outdated
#

set -e

echo "brew"
brew outdated
echo "cask"
brew outdated --cask
echo "mas"
mas outdated

#echo "brew bundle check"
#brew bundle check
