#!/usr/bin/env bash
#
# Summary: Display help for a command
#
# Usage: pm-brew help [--usage] <command>

set -e

command="$1"

if [ -z "$command" ]; then
  exec lasher _help pm-brew
fi

lasher _help pm-brew "$command"
