#!/usr/bin/env bash
#
# Summary: Exec an action over all element passed via param
#
# Usage: pm-brew _exec-action-over-all "brew:brew cask:basher" <command>

set -e

action=$2
elements=$1

if [ -z "$elements" ]; then
    pm-brew-help _exec-action-over-all
    exit 1
fi

IFS=:

for pmname in $elements;
do
    echo "${pmname}"
    unset IFS
    ${pmname} ${action}
done

