#!/usr/bin/env bash
#
# Summary:
#    Update all outdated packages
#
#    brew cask reinstall unity web-player as sudo all time
#
#    @see: https://github.com/mas-cli/mas
#
# Usage: pm-brew update
#

set -e

brew update
brew upgrade

brew upgrade --cask
#for p in $(brew list --cask); do echo "Update "$p" ..."; brew upgrade --cask $p; done

mas upgrade
